[package]
name = "codeframe"
version = "0.1.0"
edition = "2021"

[dependencies]
builtin = { path = "../builtin" }
machineinstruction = { path = "../machineinstruction" }
macrolib = { path = "../macrolib" }

[lib]
name="codeframe"
path="../allsources/codeframe.rs"