[package]
name = "machineinstruction"
version = "0.1.0"
edition = "2021"

[dependencies]
tokenizer = { path = "../tokenizer" }
opcode = { path = "../opcode" }
macrolib = { path = "../macrolib" }
regex = "1.11.1"

[lib]
name="machineinstruction"
path="../allsources/machine_instruction.rs"