cargo run allcplcode/cpltests/cpltest_assign_update.cpl
cargo run allcplcode/cpltests/cpltest_basic_arithmetic.cpl
cargo run allcplcode/cpltests/cpltest_basic_array.cpl
cargo run allcplcode/cpltests/cpltest_basic_assign.cpl
cargo run allcplcode/cpltests/cpltest_basic_break.cpl
cargo run allcplcode/cpltests/cpltest_basic_continue.cpl
cargo run allcplcode/cpltests/cpltest_basic_dict.cpl
cargo run allcplcode/cpltests/cpltest_basic_eq_ne.cpl -w
cargo run allcplcode/cpltests/cpltest_basic_eval.cpl
cargo run allcplcode/cpltests/cpltest_basic_exit.cpl
cargo run allcplcode/cpltests/cpltest_basic_exp.cpl
cargo run allcplcode/cpltests/cpltest_basic_fc.cpl
cargo run allcplcode/cpltests/cpltest_basic_foreach.cpl
cargo run allcplcode/cpltests/cpltest_basic_if.cpl
cargo run allcplcode/cpltests/cpltest_basic_literal.cpl
cargo run allcplcode/cpltests/cpltest_basic_loop.cpl
cargo run allcplcode/cpltests/cpltest_basic_lvalue.cpl
cargo run allcplcode/cpltests/cpltest_basic_matrix.cpl
cargo run allcplcode/cpltests/cpltest_basic_multi_level_struct.cpl
cargo run allcplcode/cpltests/cpltest_basic_return.cpl
cargo run allcplcode/cpltests/cpltest_basic_string.cpl
cargo run allcplcode/cpltests/cpltest_basic_struct.cpl
cargo run allcplcode/cpltests/cpltest_basic_unary.cpl
cargo run allcplcode/cpltests/cpltest_basic_while_break.cpl
cargo run allcplcode/cpltests/cpltest_basic_while_continue.cpl
cargo run allcplcode/cpltests/cpltest_basic_while00.cpl
cargo run allcplcode/cpltests/cpltest_basic_while01.cpl
cargo run allcplcode/cpltests/cpltest_break_continue_foreach.cpl
cargo run allcplcode/cpltests/cpltest_break_continue_while.cpl
cargo run allcplcode/cpltests/cpltest_builtin_append_sort.cpl
cargo run allcplcode/cpltests/cpltest_builtin_delete.cpl
cargo run allcplcode/cpltests/cpltest_builtin_insert.cpl
cargo run allcplcode/cpltests/cpltest_builtin_insert_delete_contains.cpl
cargo run allcplcode/cpltests/cpltest_builtin_io.cpl
cargo run allcplcode/cpltests/cpltest_builtin_length.cpl
cargo run allcplcode/cpltests/cpltest_builtin_locate.cpl
cargo run allcplcode/cpltests/cpltest_builtin_match_substr.cpl
cargo run allcplcode/cpltests/cpltest_builtin_push_pop.cpl
cargo run allcplcode/cpltests/cpltest_builtin_read_csv.cpl
cargo run allcplcode/cpltests/cpltest_builtin_replace_regex.cpl
cargo run allcplcode/cpltests/cpltest_builtin_replace_string.cpl
cargo run allcplcode/cpltests/cpltest_builtin_split.cpl
cargo run allcplcode/cpltests/cpltest_builtin_substring.cpl

cargo run allcplcode/cpltests/cpltest_array00.cpl
cargo run allcplcode/cpltests/cpltest_command_line_args.cpl 1 2 3 4 5
cargo run allcplcode/cpltests/cpltest_continue.cpl
cargo run allcplcode/cpltests/cpltest_dict00.cpl
cargo run allcplcode/cpltests/cpltest_dict01.cpl
cargo run allcplcode/cpltests/cpltest_eval.cpl
cargo run allcplcode/cpltests/cpltest_exp00.cpl
cargo run allcplcode/cpltests/cpltest_exp01.cpl
cargo run allcplcode/cpltests/cpltest_fc00.cpl
cargo run allcplcode/cpltests/cpltest_fc01.cpl
cargo run allcplcode/cpltests/cpltest_fc02.cpl
cargo run allcplcode/cpltests/cpltest_fc03.cpl
cargo run allcplcode/cpltests/cpltest_fc04.cpl
cargo run allcplcode/cpltests/cpltest_fc05.cpl
cargo run allcplcode/cpltests/cpltest_fc06.cpl
cargo run allcplcode/cpltests/cpltest_fc07.cpl
cargo run allcplcode/cpltests/cpltest_fc08.cpl
cargo run allcplcode/cpltests/cpltest_foreach00.cpl
cargo run allcplcode/cpltests/cpltest_foreach01.cpl
cargo run allcplcode/cpltests/cpltest_if00.cpl
cargo run allcplcode/cpltests/cpltest_include.cpl
cargo run allcplcode/cpltests/cpltest_literal00.cpl
cargo run allcplcode/cpltests/cpltest_op_overload.cpl
cargo run allcplcode/cpltests/cpltest_pass_by_reference.cpl
cargo run allcplcode/cpltests/cpltest_predicates.cpl
cargo run allcplcode/cpltests/cpltest_return00.cpl
cargo run allcplcode/cpltests/cpltest_return01.cpl
cargo run allcplcode/cpltests/cpltest_return02.cpl
cargo run allcplcode/cpltests/cpltest_reuse_var.cpl
cargo run allcplcode/cpltests/cpltest_struct00.cpl
cargo run allcplcode/cpltests/cpltest_struct01.cpl
cargo run allcplcode/cpltests/cpltest_while00.cpl
cargo run allcplcode/cpltests/cpltest_while01.cpl
cargo run allcplcode/cpltests/cpltest_while02.cpl
cargo run allcplcode/cpltests/trans.cpl allsources/transitions.txt >allsources/transitions.rs
